export interface TemplateDefinition {
  id: string;
  slug?: string;
  title: string;
  description: string;
  category: "Featured";
  stars?: string;
  nodes: any[];
  edges: any[];
}

export const PRELOADED_TEMPLATES: TemplateDefinition[] = [
  {
    id: "go",
    slug: "go",
    title: "go",
    description: "The Go programming language",
    category: "Featured",
    stars: "132.1k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -200, y: 250 },
        data: { label: "Clients" },
      },
      {
        id: "n2",
        type: "cdn",
        position: { x: 100, y: 50 },
        data: { label: "CDN" },
      },
      {
        id: "n3",
        type: "loadBalancer",
        position: { x: 300, y: 250 },
        data: { label: "Load Balancer" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 500, y: 150 },
        data: { label: "Go API" },
      },
      {
        id: "n5",
        type: "database",
        position: { x: 500, y: 350 },
        data: { label: "PostgreSQL", provider: "postgresql" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n3" },
      { id: "e2", source: "n3", target: "n4" },
      { id: "e3", source: "n4", target: "n5" },
    ],
  },
  {
    id: "flutter",
    slug: "flutter",
    title: "flutter",
    description:
      "Flutter makes it easy and fast to build beautiful apps for mobile and beyond",
    category: "Featured",
    stars: "174.8k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -200, y: 250 },
        data: { label: "iOS / Android / Web" },
      },
      {
        id: "n2",
        type: "app",
        position: { x: 100, y: 200 },
        data: { label: "Flutter App" },
      },
      {
        id: "n3",
        type: "app",
        position: { x: 350, y: 200 },
        data: { label: "Firebase Hosting" },
      },
      {
        id: "n4",
        type: "gateway",
        position: { x: 350, y: 50 },
        data: { label: "API Gateway" },
      },
      {
        id: "n5",
        type: "database",
        position: { x: 350, y: 350 },
        data: { label: "Firestore", provider: "firebase" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n4", target: "n5" },
    ],
  },
  {
    id: "react",
    slug: "react",
    title: "react",
    description: "The library for web and native user interfaces.",
    category: "Featured",
    stars: "242.5k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -200, y: 300 },
        data: { label: "User" },
      },
      {
        id: "n2",
        type: "cdn",
        position: { x: -50, y: 100 },
        data: { label: "CDN" },
      },
      {
        id: "n3",
        type: "app",
        position: { x: 150, y: 200 },
        data: { label: "React SPA" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 350, y: 200 },
        data: { label: "Next.js API" },
      },
      {
        id: "n5",
        type: "database",
        position: { x: 550, y: 200 },
        data: { label: "PostgreSQL", provider: "postgresql" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n3" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n4", target: "n5" },
    ],
  },
  {
    id: "python-sdk",
    slug: "python-sdk",
    title: "python-sdk",
    description:
      "The official Python SDK for Model Context Protocol servers and clients",
    category: "Featured",
    stars: "21.4k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -200, y: 250 },
        data: { label: "Client" },
      },
      {
        id: "n2",
        type: "worker",
        position: { x: 50, y: 200 },
        data: { label: "Python SDK" },
      },
      {
        id: "n3",
        type: "logic",
        position: { x: 250, y: 100 },
        data: { label: "MCP Server" },
      },
      {
        id: "n4",
        type: "database",
        position: { x: 250, y: 300 },
        data: { label: "Vector DB" },
      },
      {
        id: "n5",
        type: "cache",
        position: { x: 450, y: 200 },
        data: { label: "Redis" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
    ],
  },
  {
    id: "opencalw",
    slug: "opencalw",
    title: "opencalw",
    description:
      "Your own personal AI assistant. Any OS. Any Platform. The lobster way. 🦞",
    category: "Featured",
    stars: "92.7k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -200, y: 250 },
        data: { label: "User" },
      },
      {
        id: "n2",
        type: "app",
        position: { x: 0, y: 200 },
        data: { label: "AI Chat UI" },
      },
      {
        id: "n3",
        type: "worker",
        position: { x: 200, y: 100 },
        data: { label: "AI Engine" },
      },
      {
        id: "n4",
        type: "cache",
        position: { x: 400, y: 200 },
        data: { label: "Memory" },
      },
      {
        id: "n5",
        type: "database",
        position: { x: 400, y: 350 },
        data: { label: "History" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
    ],
  },
  {
    id: "meshwork-studio",
    slug: "meshwork-studio",
    title: "meshwork-studio",
    description:
      "Target decoupled microservices architecture with gRPC IPC, Redis queue, and isolated PostgreSQL database clusters.",
    category: "Featured",
    nodes: [
      {
        id: "title",
        type: "annotation",
        position: { x: -100, y: -220 },
        width: 480,
        height: 70,
        data: {
          label:
            "## Meshwork Target Microservices Architecture\nProduction goal featuring isolated databases, API Gateway routing, Redis caching/queue, and gRPC communication.",
        },
      },
      {
        id: "internet",
        type: "user",
        position: { x: 120, y: -100 },
        data: { label: "Internet Clients" },
      },
      {
        id: "cloudflare",
        type: "cdn",
        position: { x: 120, y: 20 },
        style: { width: 168, height: 72 },
        data: { label: "Cloudflare (DNS/WAF/CDN)" },
      },
      {
        id: "nginx",
        type: "loadBalancer",
        position: { x: 120, y: 140 },
        style: { width: 192, height: 72 },
        data: { label: "Nginx Proxy" },
      },
      {
        id: "gateway",
        type: "gateway",
        position: { x: 120, y: 260 },
        style: { width: 192, height: 72 },
        data: { label: "API Gateway (JWT & Validation)" },
      },
      {
        id: "auth",
        type: "microservice",
        position: { x: -280, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Auth Service" },
      },
      {
        id: "workspace",
        type: "microservice",
        position: { x: -80, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Workspace Service" },
      },
      {
        id: "mosh",
        type: "microservice",
        position: { x: 120, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Mosh Service" },
      },
      {
        id: "mcp",
        type: "microservice",
        position: { x: 320, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "MCP Service" },
      },
      {
        id: "worker",
        type: "worker",
        position: { x: 520, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Background Worker" },
      },
      {
        id: "pg",
        type: "database",
        position: { x: -280, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "PostgreSQL\n(auth_db)" },
      },
      {
        id: "dynNodes",
        type: "database",
        position: { x: -80, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "DynamoDB\n(nodes)" },
      },
      {
        id: "dynChat",
        type: "database",
        position: { x: 120, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "DynamoDB\n(chat_history)" },
      },
      {
        id: "redis",
        type: "cache",
        position: { x: 520, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "Redis\n(cache/queue)" },
      },
      {
        id: "note",
        type: "note",
        position: { x: 200, y: 400 },
        width: 200,
        height: 130,
        data: {
          label:
            "### Service Rules\n- Comm. via gRPC\n- NEVER access other DBs\n- DBs are strictly owned by respective service",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "internet",
        target: "cloudflare",
        type: "step",
        animated: true,
      },
      {
        id: "e2",
        source: "cloudflare",
        target: "nginx",
        type: "step",
        animated: true,
      },
      {
        id: "e3",
        source: "nginx",
        target: "gateway",
        type: "step",
        animated: true,
      },
      {
        id: "e4",
        source: "gateway",
        target: "auth",
        type: "step",
        animated: true,
      },
      {
        id: "e5",
        source: "gateway",
        target: "workspace",
        type: "step",
        animated: true,
      },
      {
        id: "e6",
        source: "gateway",
        target: "mosh",
        type: "step",
        animated: true,
      },
      {
        id: "e7",
        source: "gateway",
        target: "mcp",
        type: "step",
        animated: true,
      },
      {
        id: "e8",
        source: "gateway",
        target: "worker",
        type: "step",
        animated: true,
      },
      { id: "e9", source: "auth", target: "pg", type: "step" },
      { id: "e10", source: "workspace", target: "dynNodes", type: "step" },
      { id: "e11", source: "mosh", target: "dynChat", type: "step" },
      { id: "e12", source: "worker", target: "redis", type: "step" },
      {
        id: "e13",
        source: "workspace",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e14",
        source: "mosh",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e15",
        source: "mcp",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e16",
        source: "mcp",
        target: "workspace",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e17",
        source: "worker",
        target: "workspace",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
    ],
  },
];
