import { describe, it, expect } from "vitest";
import { validateAndRepairCanvas } from "@/lib/ai-canvas-utils";

describe("Mosh AI Canvas Node & Edge Generation Unit Tests", () => {
  describe("validateAndRepairCanvas", () => {
    it("should return null for invalid or empty inputs", () => {
      expect(validateAndRepairCanvas(null)).toBeNull();
      expect(validateAndRepairCanvas(undefined)).toBeNull();
      expect(validateAndRepairCanvas({})).toBeNull();
      expect(
        validateAndRepairCanvas({ nodes: "invalid", edges: [] }),
      ).toBeNull();
    });

    it("should parse and normalize valid 3-tier architecture generated by Mosh", () => {
      const rawPayload = {
        nodes: [
          {
            id: "node-user",
            type: "user",
            position: { x: 100, y: 200 },
            data: { label: "End User" },
          },
          {
            id: "node-cdn",
            type: "cdn",
            position: { x: 380, y: 200 },
            data: { label: "Cloudflare CDN" },
          },
          {
            id: "node-gw",
            type: "gateway",
            position: { x: 660, y: 200 },
            data: { label: "Kong API Gateway" },
          },
          {
            id: "node-db",
            type: "postgres", // Alias that needs normalization to "database"
            position: { x: 940, y: 120 },
            data: { label: "Main PostgreSQL DB" },
          },
          {
            id: "node-cache",
            type: "redis", // Alias that needs normalization to "cache"
            position: { x: 940, y: 320 },
            data: { label: "Redis Cluster" },
          },
        ],
        edges: [
          { id: "e1", source: "node-user", target: "node-cdn" },
          { id: "e2", source: "node-cdn", target: "node-gw" },
          { id: "e3", source: "node-gw", target: "node-db" },
          { id: "e4", source: "node-gw", target: "node-cache" },
        ],
      };

      const result = validateAndRepairCanvas(rawPayload);
      expect(result).not.toBeNull();
      expect(result!.nodes).toHaveLength(5);
      expect(result!.edges).toHaveLength(4);

      // Check type alias normalizations
      const dbNode = result!.nodes.find((n) => n.id === "node-db");
      expect(dbNode).toBeDefined();
      expect(dbNode!.type).toBe("database");
      expect(dbNode!.style?.width).toBe(144);
      expect(dbNode!.style?.height).toBe(120);

      const cacheNode = result!.nodes.find((n) => n.id === "node-cache");
      expect(cacheNode).toBeDefined();
      expect(cacheNode!.type).toBe("cache");
      expect(cacheNode!.style?.width).toBe(144);
      expect(cacheNode!.style?.height).toBe(120);

      const gwNode = result!.nodes.find((n) => n.id === "node-gw");
      expect(gwNode).toBeDefined();
      expect(gwNode!.type).toBe("gateway");
      expect(gwNode!.style?.width).toBe(192);
      expect(gwNode!.style?.height).toBe(72);
    });

    it("should filter out orphan edges pointing to nonexistent nodes", () => {
      const rawPayload = {
        nodes: [
          { id: "app-1", type: "microservice", position: { x: 100, y: 100 } },
          { id: "db-1", type: "database", position: { x: 300, y: 100 } },
        ],
        edges: [
          { id: "valid-edge", source: "app-1", target: "db-1" },
          { id: "orphan-source", source: "ghost-node", target: "db-1" },
          { id: "orphan-target", source: "app-1", target: "ghost-node" },
        ],
      };

      const result = validateAndRepairCanvas(rawPayload);
      expect(result).not.toBeNull();
      expect(result!.nodes).toHaveLength(2);
      expect(result!.edges).toHaveLength(1);
      expect(result!.edges[0].id).toBe("valid-edge");
    });

    it("should deduplicate duplicate node IDs and repair missing coordinates", () => {
      const rawPayload = {
        nodes: [
          { id: "dup-id", type: "server" }, // Missing position
          { id: "dup-id", type: "server" }, // Duplicate ID & missing position
        ],
        edges: [],
      };

      const result = validateAndRepairCanvas(rawPayload);
      expect(result).not.toBeNull();
      expect(result!.nodes).toHaveLength(2);
      expect(result!.nodes[0].id).toBe("dup-id");
      expect(result!.nodes[1].id).toBe("dup-id-1");

      // Auto assigned positions
      expect(result!.nodes[0].position.x).toBe(100);
      expect(result!.nodes[1].position.x).toBe(320);
    });

    it("should handle nested container hierarchy (e.g., VPC with subnets and services)", () => {
      const rawPayload = {
        nodes: [
          {
            id: "vpc-1",
            type: "vpc",
            position: { x: 50, y: 50 },
            data: { label: "Production VPC" },
          },
          {
            id: "service-1",
            type: "microservice",
            parentId: "vpc-1",
            position: { x: 80, y: 120 },
            data: { label: "Payment Service" },
          },
        ],
        edges: [],
      };

      const result = validateAndRepairCanvas(rawPayload);
      expect(result).not.toBeNull();
      const childNode = result!.nodes.find((n) => n.id === "service-1");
      expect(childNode).toBeDefined();
      expect(childNode!.parentId).toBe("vpc-1");
      expect(childNode!.extent).toBe("parent");
    });
  });
});
