#!/usr/bin/env npx tsx
/**
 * Creates one local-only development configuration for the Node app, Go auth
 * service, and Docker Compose. Production secrets must come from a secret
 * manager; this file is deliberately ignored by Git.
 */
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseEnv } from "dotenv";

const rootDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const envPath = path.join(rootDir, ".env");
const force = process.argv.includes("--force") || process.argv.includes("-f");

function randomBase64(bytes = 32): string {
  return crypto.randomBytes(bytes).toString("base64");
}

function randomHex(bytes = 24): string {
  return crypto.randomBytes(bytes).toString("hex");
}

function publicKeyFromSeed(seedBase64: string): string {
  const seed = Buffer.from(seedBase64, "base64");
  const privateKey = crypto.createPrivateKey({
    key: Buffer.concat([
      Buffer.from([
        0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70,
        0x04, 0x22, 0x04, 0x20,
      ]),
      seed,
    ]),
    format: "der",
    type: "pkcs8",
  });
  const spki = crypto.createPublicKey(privateKey).export({
    format: "der",
    type: "spki",
  });
  return spki.subarray(-32).toString("base64");
}

if (fs.existsSync(envPath) && !force) {
  const existing = parseEnv(fs.readFileSync(envPath));
  const required = [
    "WORKSPACE_DATABASE_URL",
    "TEAM_DATABASE_URL",
    "AI_DATABASE_URL",
    "METRICS_DATABASE_URL",
    "REDIS_URL",
    "AUTH_DATABASE_URL",
    "AUTH_REDIS_URL",
    "AUTH_IP_HASH_KEY",
    "AUTH_ENCRYPTION_KEY",
    "AUTH_ASSERTION_PRIVATE_KEY",
    "AUTH_ASSERTION_PUBLIC_KEY",
    "ENCRYPTION_KEY",
  ];
  const missing = required.filter((key) => !existing[key]?.trim());
  const reusedSigningSeed =
    existing.AUTH_ASSERTION_PRIVATE_KEY &&
    existing.AUTH_ASSERTION_PUBLIC_KEY === existing.AUTH_ASSERTION_PRIVATE_KEY;
  if (missing.length > 0 || reusedSigningSeed) {
    console.error("Existing .env was left untouched because it is incomplete.");
    if (missing.length > 0) {
      console.error(`Missing required keys: ${missing.join(", ")}`);
    }
    if (reusedSigningSeed) {
      console.error(
        "AUTH_ASSERTION_PUBLIC_KEY contains private signing material; it must be replaced with the derived public key.",
      );
    }
    console.error(
      "Back up any custom values, then run `npm run setup -- --force` to create a complete local configuration.",
    );
    process.exit(1);
  }
  console.log(
    ".env already exists and contains the required local configuration.",
  );
  process.exit(0);
}

const assertionPrivateKey = randomBase64();
const assertionPublicKey = publicKeyFromSeed(assertionPrivateKey);
const postgresPassword = "postgres_dev_password";
const authDatabasePassword = "auth_dev_password";
const workspaceDatabasePassword = "workspace_dev_password";
const teamDatabasePassword = "team_dev_password";
const aiDatabasePassword = "ai_dev_password";
const metricsDatabasePassword = "metrics_dev_password";

const environment = `# Generated by npm run setup for local development. Never use these values in production.
NODE_ENV=development
PORT=5000
APP_URL=http://localhost:5000
APP_PUBLIC_URL=http://localhost:5000
FRONTEND_URL=http://localhost:5000

# Local Docker data services
POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERUSER_PASSWORD=${postgresPassword}
AUTH_DB_PASSWORD=${authDatabasePassword}
WORKSPACE_DB_PASSWORD=${workspaceDatabasePassword}
TEAM_DB_PASSWORD=${teamDatabasePassword}
AI_DB_PASSWORD=${aiDatabasePassword}
METRICS_DB_PASSWORD=${metricsDatabasePassword}
JENKOS_DB_PASSWORD=${aiDatabasePassword}
AUTH_DATABASE_URL=postgresql://auth_app:${authDatabasePassword}@localhost:5434/auth_db
WORKSPACE_DATABASE_URL=postgresql://workspace_app:${workspaceDatabasePassword}@localhost:5434/workspace_db
TEAM_DATABASE_URL=postgresql://team_app:${teamDatabasePassword}@localhost:5434/team_db
AI_DATABASE_URL=postgresql://ai_app:${aiDatabasePassword}@localhost:5434/ai_db
METRICS_DATABASE_URL=postgresql://metrics_app:${metricsDatabasePassword}@localhost:5434/metrics_db
REDIS_URL=redis://localhost:6379
AUTH_REDIS_URL=redis://localhost:6379
CANVAS_DDB_TABLE=meshwork-canvas
AWS_REGION=us-east-1
DYNAMODB_ENDPOINT=http://localhost:8000
AWS_ACCESS_KEY_ID=local
AWS_SECRET_ACCESS_KEY=local

# Local cryptographic material. The Node app receives only the public assertion key.
SESSION_SECRET=${randomBase64()}
METRICS_BEARER_TOKEN=${randomHex(16)}
INTERNAL_API_KEY=${randomHex()}
AUTH_INTERNAL_KEY=${randomHex()}
AUTH_IP_HASH_KEY=${randomBase64()}
AUTH_ENCRYPTION_KEY=${randomBase64()}
AUTH_ASSERTION_PRIVATE_KEY=${assertionPrivateKey}
AUTH_ASSERTION_PUBLIC_KEY=${assertionPublicKey}
ENCRYPTION_KEY=${randomBase64()}
AUTH_SERVICE_URL=http://localhost:8081

# Optional integrations
GEMINI_API_KEY=
OPENROUTER_API_KEY=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
EMAIL_FROM=
CAPTCHA_PROVIDER=
CAPTCHA_SECRET=
`;

fs.writeFileSync(envPath, environment, { encoding: "utf8", mode: 0o600 });
console.log(
  "Created .env with local-only services and fresh development keys.",
);
console.log("Start the complete local stack with: docker compose up --build");
console.log("Open http://localhost:5000 when the services are healthy.");
